### ISSUE TITLE
Draw All Shapes

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/geolocator#32]
We already had the code for the Point demo and this app was grown from that code.  The script now exists as part of the `PointPicker` component.  

The desire is to be able to draw [any of the seven GeoJSON geometry types](https://datatracker.ietf.org/doc/html/rfc7946#section-1.4).  There are existing open source libraries that do this and they were investigated.  The developers believe it would not take a large feat to use one of those libraries in conjunction with this codebase.

**Comment by thehabes** [comment]
See an existing library in use at https://geojson.io

**Comment by yashaswini-slu** [comment]
Sub Issues: 
- https://github.com/CenterForDigitalHumanities/geolocator/issues/61
- https://github.com/CenterForDigitalHumanities/geolocator/issues/62
- https://github.com/CenterForDigitalHumanities/geolocator/issues/63
