### ISSUE TITLE
Download to local machine

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/geolocator#33]
If the goal is to "have a resource to walk away with", that may not mean actually saving it into a database. There should be an option to save to the client machine, which they can then alter and take with them to save it where they want to.

**Comment by em-henken** [comment]
When you say "resource", do you mean the JSON object presented at the end? If so, what kind of file would this be saved as?

**Comment by em-henken** [comment]
I plan on creating a "download" icon on the page where the final JSON resource is presented. When clicked, a File explorer window will pop up and the user will be able to choose where the file is saved and how it is called.
