### ISSUE TITLE
@context validation

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/geolocator#40]
Determine what course of action to take for `@context` value detection and validation.  The alerts are not a great UX, but the user should be given warnings for mistakes and errors.

**Comment by tobradovic** [comment]
Approach for the ticket:
- Where buttons are required
  - Option1: Disable button until all required text fields are valid. To show that the text field is required, put an asterisk next to the label.
  - Option2: If a user tries to proceed with a bad input, produce a red outline on the text box as well as a message below. The message will be the same message that is currently in the alert.
- Where buttons are optional
    - Provide a warning under the text box if URI can not be resolved. This can be done with a yellow outline and a message explaining that the URI will not be resolved
