### ISSUE TITLE
"@context" : 3 appearing in JSON preview

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/geolocator#54]
On http://geo.rerum.io/navPlace.html.  Use the resource URI https://iiif.io/api/cookbook/recipe/0154-geo-extension/manifest.json.

If you click and continue through the warnings, in the end the preview has
```
{
	"@context": 3,
	"id": "https://iiif.io/api/cookbook/recipe/0154-geo-extension/manifest.json",
	"type": "Manifest",
	"label": {
		"it": [
			"Bronzo Laocoonte e i suoi figli"
		]
	}
	...
```

The @context for this object should be whatever its original @context value was and additionally `"http://iiif.io/api/extension/navplace/context.json",  "http://iiif.io/api/presentation/3/context.json"`.  If the original @context was not present or was a String, it needs to become an Array of Strings.  If the original @context was array, these values should be added to that Array.  All context.json links should only appear once in the Array.  The resulting @context for the `navPlace.html` flow will ALWAYS be in the form of

```
"@context": [
        "http://some/original/context.json",
        "http://iiif.io/api/extension/navplace/context.json",
        "http://iiif.io/api/presentation/3/context.json"
]
```

The resulting @context for the `annotate.html` flow will ALWAYS be in the form of
```
"@context": [
        "http://some/original/context.json",
        "http://www.w3.org/ns/anno.jsonld",
	"https://geojson.org/geojson-ld/geojson-context.jsonld"
]
```

**Note that order matters**, and the last two values in the @context arrays should always be "http://iiif.io/api/extension/navplace/context.json" and "http://iiif.io/api/presentation/3/context.json"  or  "http://www.w3.org/ns/anno.jsonld" and "https://geojson.org/geojson-ld/geojson-context.jsonld" specifically in that order.  Most of the time, it just ends up being those two context.json links.

**Comment by thehabes** [comment]
For example, the result of taking `https://iiif.io/api/cookbook/recipe/0154-geo-extension/manifest.json` all the way through and ignoring the warnings would replace the existing `navPlace` property with the new geometry selected and have the context 

```
"@context": [
        "http://iiif.io/api/extension/navplace/context.json",
        "http://iiif.io/api/presentation/3/context.json"
]
```
The error seems to only be for resource URIs that already contain one or both of these entries in the @context.

**Comment by tobradovic** [comment]
If the original context contains `http://iiif.io/api/presentation/2/context.json` (an outdated IIIF format), should we still add `http://iiif.io/api/presentation/3/context.json` to the context?
